org: serverlessquiz

service: quiz

provider:
  name: aws
  runtime: nodejs20.x
  region: ${env:AWS_REGION}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:PutItem
        - dynamodb:GetItem
        - dynamodb:DeleteItem
        - dynamodb:UpdateItem
        - dynamodb:Scan
        - dynamodb:Query
      Resource:
        - arn:aws:dynamodb:eu-north-1:615299752906:table/UserTable
        - arn:aws:dynamodb:eu-north-1:615299752906:table/QuizTable
        - arn:aws:dynamodb:eu-north-1:615299752906:table/ScoreTable
  environment:
    SECRET: ${env:SECRET}
    USER_TABLE: UserTable
    QUIZ_TABLE: QuizTable
    SCORE_TABLE: ScoreTable

functions:
  Login:
    handler: functions/Login/index.handler
    events:
      - httpApi:
          path: /auth/login
          method: post
  Signup:
    handler: functions/Signup/index.handler
    events:
      - httpApi:
          path: /auth/signup
          method: post
  CreateQuiz:
    handler: functions/Quiz/createQuiz.handler
    events:
      - httpApi:
          path: /quiz
          method: post
  GetQuiz:
    handler: functions/Quiz/getQuiz.handler
    events:
      - httpApi:
          path: /quiz/{quizId}
          method: get
  GetAllQuiz:
    handler: functions/Quiz/getAllQuiz.handler
    events:
      - httpApi:
          path: /quiz
          method: get
  DeleteQuiz:
    handler: functions/Quiz/deleteQuiz.handler
    events:
      - httpApi:
          path: /quiz/{quizId}
          method: delete
  addQuestion:
    handler: functions/Quiz/questionQuiz.handler
    events:
      - httpApi:
          path: /quiz/question
          method: post
  getLeaderboard:
    handler: functions/Leaderboard/leaderboard.handler
    events:
      - httpApi:
          path: /leaderboard/{quizId}
          method: get
  AddPoint:
    handler: functions/Leaderboard/points.handler
    events:
      - httpApi:
          path: /leaderboard/points
          method: post
resources:
  Resources:
    UserTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: UserTable
        AttributeDefinitions:
          - AttributeName: username
            AttributeType: S
        KeySchema:
          - AttributeName: username
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST

    QuizTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: QuizTable
        AttributeDefinitions:
          - AttributeName: quizId
            AttributeType: S
        KeySchema:
          - AttributeName: quizId
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST

    ScoreTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ScoreTable
        AttributeDefinitions:
          - AttributeName: quizId
            AttributeType: S
          - AttributeName: username
            AttributeType: S
        KeySchema:
          - AttributeName: quizId
            KeyType: HASH
          - AttributeName: username
            KeyType: RANGE
        BillingMode: PAY_PER_REQUEST
